### ISSUE TITLE
Minimum MetalJS version warning?

### ISSUE THREAD

**Issue by ssmith353** [bryceosterhaus/metal-devtools#11]
Hey Bryce this is AWESOME. I've missed the react dev tools since we switched to metal! 

A tiny improvement is on the initial warning, it would be helpful to have a minimum metalJs version warning. 

Our project is a few versions behind, so this didn't show anything other than the reload warning. 

https://github.com/bryceosterhaus/metal-devtools/blob/master/frontend/components/InitialWarning.js#L6

**Comment by bryceosterhaus** [comment]
released in https://github.com/bryceosterhaus/metal-devtools/releases/tag/v1.1.0
