### ISSUE TITLE
Add element highlighting to elements pane

### ISSUE THREAD

**Issue by bryceosterhaus** [bryceosterhaus/metal-devtools#5]
Similar to how react does this, we should add functionality that allows us to inspect a certain node in the DOM and then show that corresponding metal component. Also, we should provide capability to highlight dom node after selecting its metal-component on the Metal.js tab.

**Comment by bryceosterhaus** [comment]
Available in https://github.com/bryceosterhaus/metal-devtools/releases/tag/v1.0.2-alpha

**Comment by jbalsas** [comment]
😱 😱 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏
