### ISSUE TITLE
Highlight component element in dom

### ISSUE THREAD

**Issue by jbalsas** [bryceosterhaus/metal-devtools#7]
In order to easily identify the components on a page, it would be nice to be able to highlight the component `element` in the live page same way as when you're hovering over the DOM panel in chrome devtools.

Possible reference might be:

https://developer.chrome.com/extensions/debugger#method-sendCommand
https://chromedevtools.github.io/debugger-protocol-viewer/tot/DOM/#method-highlightNode

**Comment by jbalsas** [comment]
Maybe also relevant is Brackets `HighlightAgent` implementation:

https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/src/LiveDevelopment/Agents/HighlightAgent.js#L93

**Comment by bryceosterhaus** [comment]
Added feature for testing on [this branch](https://github.com/bryceosterhaus/metal-devtools/tree/beta-rewrite)

**Comment by bryceosterhaus** [comment]
released in https://github.com/bryceosterhaus/metal-devtools/releases/tag/v1.1.0
